### ISSUE TITLE
'=' not '==' ?

### ISSUE THREAD

**Issue by Paquette1111** [andreitoma8/ERC721-Staking#1]
https://github.com/andreitoma8/ERC721-Staking/blob/8cc7d3ae810b96554570c9456ab8eea8c909086f/contracts/ERC721Staking.sol#L82

Should line 82 here be `stakerAddress[_tokenIds[i]] = address(0);` rather than `==`

note: I am new to solidity and I want to make sure I'm understanding this correctly. thanks.

**Comment by andreitoma8** [comment]
Yes, that is right, thank you very much for raising the issue!
