### ISSUE TITLE
Why do you create three smart-contracts instead of two?

### ISSUE THREAD

**Issue by GorgeousPuree** [andreitoma8/ERC721-Staking#2]
Why do you think it's better to separate token and staking smart-contracts? Is there any sense, but code segregation? We could combine these two smart-contracts into single one. If it wasn't blockchain development I would separate them into two microservices, but when it comes to paying for deployment, it's cheaper to have one sc.

**Comment by andreitoma8** [comment]
My toughts were just to make it easier to understand and make it more modular for people who would like to use the Staking Contract with a Token that is already deployed. If you want to combine the two contracts I don’t see any reason not to.

**Comment by GorgeousPuree** [comment]
Thanks for the answer.
