### ISSUE TITLE
existing nft contract? 

### ISSUE THREAD

**Issue by maddefientist** [andreitoma8/ERC721-Staking#3]
Is there a way to use an existing nft smart contract? 

Have tried renaming nft.address in the deploy script, passing the contract address in constructor (wont let me verify with constructor arguments) but it doesnt seem to like anything except the contract deployed alongside the token and staking. 

Where would I configure this?

**Comment by andreitoma8** [comment]
In the deploy script, instead of passing nft.address, pass your contract's address as a string

**Comment by maddefientist** [comment]
Thanks, I did try that. The stake function refuses to accept the NFT. When
I try with an nft id i dont own, it gives proper error "you cant stake what
you dont own" , but when attempting to stake properly receive just "fail" -
goerli tx
hash 0xa98c5ad32f66c259265d14305d988e5229c839a5c37bcbfffe2035cfd27aee57

**Comment by andreitoma8** [comment]
The "you cant stake what you dont own" error is given when you're trying to stake a NFT that is not yours(see require statement at line 61 in the SC). Just to make sure, are you approvin the NFT transfer before trying to stake?

**Comment by maddefientist** [comment]
Yes, that makes sense if you don’t own the Nft , but the other error
shouldn’t appear. The Nft should be approved for transfer, unless I must
approve it within this staking contract first ..?

**Comment by maddefientist** [comment]
So I approve each tokenId with the NFT contract for movement, and the staking works. Thank you. Are you aware of any process that makes this flow happen together? Or must all dApps be built to approve specific token ID in your wallet with the NFT collection before staking in Staking contract? 

Thanks for your help, if you don't have an answer to simplifying this process please feel free to close the issue

**Comment by andreitoma8** [comment]
You can use the setApprovalForAll function the first time a user stakes a token so you don’t have to do it with each token every time, as OpenSea does it for example.
