### ISSUE TITLE
Trying to understand how the rewardsToken safeTransfer work

### ISSUE THREAD

**Issue by jgc138** [andreitoma8/ERC721-Staking#4]
Hello! 

Thank you for making these contracts available for free.

I have a question that that it'd be really helpful to get an explanation from.

In the staking contract, when calling `rewardsToken.safeTransfer(msg.sender, rewards);`, I'm assuming the `msg.sender` in the ERC20 contract is going to be the `ERC721Staking` contract that's calling it

https://github.com/andreitoma8/ERC721-Staking/blob/14d095f9f4a818601eb2d2aa37b6b189826ac878/contracts/ERC721Staking.sol#L110

So basically it'll call `_transfer(**ERC721Staking Address**, **Rewardee Address**, **amount**);`  in the ERC20 contract.

So what I'm trying to understand is how does the `ERC721Staking` have any tokens to start with to transfer to the rewardee ?

The rewards token constructor https://github.com/andreitoma8/ERC721-Staking/blob/14d095f9f4a818601eb2d2aa37b6b189826ac878/contracts/Contracts/RewardToken.sol#L12

will mint to the `msg.sender` but that's the address that deploys the contract and not the `ERC721Staking` contract.

Apologies if this is a silly question, I am a newbie to smart contract development :)

Thank you!

**Comment by andreitoma8** [comment]
You'll have to send the Tokens to the Staking Smart Contract yourself so it can distribute rewards. The Token Contract mints 1000000 tokens for whoever deploys it.

**Comment by jgc138** [comment]
Thanks for your response @andreitoma8
